S = [
    {
    "target":"class",
      "outlook":"sunny",
      "humidity":"high",
      "windy":"false",
      "class":"n"
    },
    {
    "target":"class",
      "outlook":"sunny",
      "humidity":"high",
      "windy":"true",
      "class":"n"
    },
    {
    "target":"class",
      "outlook":"sunny",
      "humidity":"high",
      "windy":"false",
      "class":"p"
    },
    {
    "target":"class",
      "outlook":"sunny",
      "humidity":"high",
      "windy":"false",
      "class":"p"
    },
    {
    "target":"class",
      "outlook":"sunny",
      "humidity":"normal",
      "windy":"false",
      "class":"p"
    },
    {
    "target":"class",
      "outlook":"sunny",
      "humidity":"normal",
      "windy":"true",
      "class":"n"
    },
    {
    "target":"class",
      "outlook":"sunny",
      "humidity":"normal",
      "windy":"true",
      "class":"p"
    },
    {
    "target":"class",
      "outlook":"sunny",
      "humidity":"high",
      "windy":"false",
      "class":"n"
    },
    {
    "target":"class",
      "outlook":"sunny",
      "humidity":"normal",
      "windy":"false",
      "class":"p"
    },
    {
    "target":"class",
      "outlook":"sunny",
      "humidity":"normal",
      "windy":"false",
      "class":"n"
    },
    {
    "target":"class",
      "outlook":"sunny",
      "humidity":"normal",
      "windy":"true",
      "class":"n"
    },
    {
    "target":"class",
      "outlook":"sunny",
      "humidity":"high",
      "windy":"true",
      "class":"n"
    },
    {
    "target":"class",
      "outlook":"sunny",
      "humidity":"normal",
      "windy":"false",
      "class":"n"
    },
    {
    "target":"class",
      "outlook":"sunny",
      "humidity":"high",
      "windy":"true",
      "class":"p"
    }
    ]